/// Pre-submission checks for a stamped Surge app. Each check inspects the
/// app directory (and manifest) and returns pass / warn / fail with a
/// human-actionable detail. The CLI renders the report and exits 1 on any
/// fail. Checks are static-analysis only (no network, no device); the one
/// exception - running `flutter test` - is opt-out via the CLI.
library;

import 'dart:io';

enum CheckStatus { pass, warn, fail }

class CheckResult {
  const CheckResult(this.name, this.status, this.detail);
  final String name;
  final CheckStatus status;
  final String detail;
}

String _read(File f) => f.readAsStringSync();

String _rel(File f, String appDir) =>
    f.path.substring(appDir.length + 1).replaceAll('\\', '/');

List<File> _dartFilesUnder(Directory dir) => !dir.existsSync()
    ? const []
    : dir
        .listSync(recursive: true)
        .whereType<File>()
        .where((f) => f.path.endsWith('.dart'))
        .toList();

/// Runs every static check against [appDir]. [runTests] additionally shells
/// out to `flutter test` (slow; needs the Flutter SDK on PATH).
Future<List<CheckResult>> runChecks(
  String appDir,
  Map manifest, {
  bool runTests = false,
}) async {
  final results = <CheckResult>[];
  File at(String rel) => File('$appDir/$rel');
  Directory dirAt(String rel) => Directory('$appDir/$rel');

  // -- 1. Feature stubs must be replaced (stub-only fails Apple 4.3). -------
  final stubMarkers = ['This tab is a wired stub', 'Your feature goes here'];
  final stubbed = <String>[
    for (final f in _dartFilesUnder(dirAt('lib/features')))
      if (stubMarkers.any(_read(f).contains)) _rel(f, appDir),
  ];
  results.add(
    stubbed.isEmpty
        ? const CheckResult('feature stubs', CheckStatus.pass,
            'no generated stubs left in lib/features')
        : CheckResult('feature stubs', CheckStatus.fail,
            'still stubs (Apple 4.3 rejects stub-only): '
            '${stubbed.join(', ')}'),
  );

  // -- 2 + 3. Seams flipped to live backends. -------------------------------
  final bootstrap = at('lib/app/bootstrap.dart');
  final bootstrapSrc = bootstrap.existsSync() ? _read(bootstrap) : '';
  results.add(
    bootstrapSrc.contains('useFirebase = true')
        ? const CheckResult(
            'firebase seam', CheckStatus.pass, 'useFirebase = true')
        : const CheckResult('firebase seam', CheckStatus.fail,
            'useFirebase is still false - the release would ship mock auth '
            '(lib/app/bootstrap.dart)'),
  );
  results.add(
    bootstrapSrc.contains('useRevenueCat = true')
        ? const CheckResult(
            'revenuecat seam', CheckStatus.pass, 'useRevenueCat = true')
        : const CheckResult('revenuecat seam', CheckStatus.fail,
            'useRevenueCat is still false - purchases would be mocked '
            '(lib/app/bootstrap.dart)'),
  );

  // -- 4. firebase_options must be the real flutterfire output. -------------
  final fbOptions = at('lib/firebase_options.dart');
  results.add(
    !fbOptions.existsSync()
        ? const CheckResult('firebase options', CheckStatus.fail,
            'lib/firebase_options.dart missing - run flutterfire configure')
        : _read(fbOptions).contains('PLACEHOLDER')
            ? const CheckResult('firebase options', CheckStatus.fail,
                'still the placeholder - run flutterfire configure')
            : const CheckResult('firebase options', CheckStatus.pass,
                'generated by flutterfire'),
  );

  // -- 5. Apple privacy manifest present AND in the Xcode project. ----------
  final privacyFile = at('ios/Runner/PrivacyInfo.xcprivacy');
  final pbxproj = at('ios/Runner.xcodeproj/project.pbxproj');
  if (!dirAt('ios').existsSync()) {
    results.add(const CheckResult('privacy manifest', CheckStatus.fail,
        'no ios/ folder yet - run scripts/forge.sh (flutter create) first'));
  } else if (!privacyFile.existsSync()) {
    results.add(const CheckResult('privacy manifest', CheckStatus.fail,
        'ios/Runner/PrivacyInfo.xcprivacy missing - forge copies it from '
        'legal/'));
  } else if (pbxproj.existsSync() &&
      !_read(pbxproj).contains('PrivacyInfo.xcprivacy')) {
    results.add(const CheckResult('privacy manifest', CheckStatus.warn,
        'file exists but is not referenced by the Xcode project - add it to '
        'the Runner target in Xcode'));
  } else {
    results.add(const CheckResult(
        'privacy manifest', CheckStatus.pass, 'present in ios/Runner'));
  }

  // -- 6. ATT usage string when the app tracks. ------------------------------
  final tracking =
      ((manifest['legal'] as Map?)?['data_practices'] as Map?)?['tracking'] ==
          true;
  if (!tracking) {
    results.add(const CheckResult('att string', CheckStatus.pass,
        'tracking=false - no ATT prompt required'));
  } else {
    final plist = at('ios/Runner/Info.plist');
    final hasString = plist.existsSync() &&
        _read(plist).contains('NSUserTrackingUsageDescription');
    results.add(
      hasString
          ? const CheckResult('att string', CheckStatus.pass,
              'NSUserTrackingUsageDescription set')
          : const CheckResult('att string', CheckStatus.fail,
              'tracking=true but Info.plist has no '
              'NSUserTrackingUsageDescription - Apple rejects at upload'),
    );
  }

  // -- 7. Secrets hygiene: no hardcoded RevenueCat/PostHog keys in source. --
  final keyPattern = RegExp('(appl|goog|phc)_[A-Za-z0-9]{12,}');
  final leaks = <String>[
    for (final f in _dartFilesUnder(dirAt('lib')))
      if (keyPattern.hasMatch(_read(f))) _rel(f, appDir),
  ];
  results.add(
    leaks.isEmpty
        ? const CheckResult('secrets hygiene', CheckStatus.pass,
            'no hardcoded store/analytics keys; REVENUECAT_KEY and '
            'POSTHOG_KEY flow via --dart-define')
        : CheckResult('secrets hygiene', CheckStatus.fail,
            'hardcoded key in: ${leaks.join(', ')} - move it to '
            '--dart-define'),
  );

  // -- 7b. Analytics doctrine present. ---------------------------------------
  results.add(
    at('ANALYTICS.md').existsSync()
        ? const CheckResult('analytics doc', CheckStatus.pass,
            'ANALYTICS.md present - run its TestFlight checklist')
        : const CheckResult('analytics doc', CheckStatus.warn,
            'ANALYTICS.md missing (older stamp) - copy the template; it '
            'carries the dashboards + no-PII rules'),
  );

  // -- 8. Legal artifacts generated. -----------------------------------------
  final legalOk =
      at('legal/legal.json').existsSync() && at('legal/privacy.md').existsSync();
  results.add(
    legalOk
        ? const CheckResult('legal artifacts', CheckStatus.pass,
            'legal/ generated - confirm the site shows it at legal.privacy_url')
        : const CheckResult('legal artifacts', CheckStatus.fail,
            'legal/ missing - run tools/legal_gen (forge step 4), register '
            'legal.json on the Surge site'),
  );

  // -- 9. Store metadata generated and within hard limits. -------------------
  final iosMeta = 'fastlane/metadata/en-US';
  if (!at('$iosMeta/name.txt').existsSync()) {
    results.add(const CheckResult('store metadata', CheckStatus.fail,
        'fastlane/metadata missing - run tools/store_gen'));
  } else {
    String txt(String rel) =>
        at(rel).existsSync() ? _read(at(rel)).trim() : '';
    final over = <String>[
      if (txt('$iosMeta/subtitle.txt').length > 30) 'ios subtitle>30',
      if (txt('$iosMeta/keywords.txt').length > 100) 'ios keywords>100',
      if (txt('fastlane/metadata/android/en-US/short_description.txt')
              .length >
          80)
        'play short_description>80',
    ];
    results.add(
      over.isEmpty
          ? const CheckResult(
              'store metadata', CheckStatus.pass, 'present, within limits')
          : CheckResult('store metadata', CheckStatus.fail,
              'over store limits: ${over.join(', ')} - fix the manifest and '
              'regenerate'),
    );
  }

  // -- 10. Version sanity. ----------------------------------------------------
  final pubspec = at('pubspec.yaml');
  final versionMatch = pubspec.existsSync()
      ? RegExp(r'^version:\s*(\d+\.\d+\.\d+\+\d+)', multiLine: true)
          .firstMatch(_read(pubspec))
      : null;
  results.add(
    versionMatch != null
        ? CheckResult('version', CheckStatus.pass,
            '${versionMatch.group(1)} - confirm this is the intended release')
        : const CheckResult('version', CheckStatus.fail,
            'pubspec version missing or not x.y.z+n'),
  );

  // -- 11. Backend shipped (deploy is on you). --------------------------------
  results.add(
    at('firestore.rules').existsSync()
        ? const CheckResult('backend', CheckStatus.pass,
            'rules present - deploy before release: firebase deploy --only '
            'firestore,functions')
        : const CheckResult('backend', CheckStatus.warn,
            'no firestore.rules (older stamp) - copy the backend template'),
  );

  // -- 12. Tests (optional; the slow one). ------------------------------------
  if (runTests) {
    final r = await Process.run('flutter', ['test'],
        workingDirectory: appDir, runInShell: true);
    results.add(
      r.exitCode == 0
          ? const CheckResult('flutter test', CheckStatus.pass, 'green')
          : CheckResult('flutter test', CheckStatus.fail,
              (r.stdout.toString().trim().split('\n')..retainWhere(
                      (l) => l.contains('failed') || l.contains('Error')))
                  .take(3)
                  .join(' | ')),
    );
  }

  return results;
}

/// Renders the report; returns the exit code (1 if any fail).
int report(List<CheckResult> results, StringSink out) {
  const labels = {
    CheckStatus.pass: 'PASS',
    CheckStatus.warn: 'WARN',
    CheckStatus.fail: 'FAIL',
  };
  for (final r in results) {
    out.writeln('[${labels[r.status]}] ${r.name} - ${r.detail}');
  }
  final fails = results.where((r) => r.status == CheckStatus.fail).length;
  final warns = results.where((r) => r.status == CheckStatus.warn).length;
  out.writeln(fails == 0
      ? 'ship check: ready${warns > 0 ? ' ($warns warning${warns == 1 ? '' : 's'})' : ''}.'
      : 'ship check: NOT ready - $fails blocker${fails == 1 ? '' : 's'}, '
          '$warns warning${warns == 1 ? '' : 's'}.');
  return fails == 0 ? 0 : 1;
}
