/// Generates a product-spec skeleton from a parsed `surge.manifest.yaml`,
/// modeled on Ladle's original-spec.md (the structure that shipped). Fills
/// everything derivable from the manifest - tabs, screen inventory with
/// stable IDs, gating table, monetization mechanics, brand - and leaves
/// `**TODO**` markers where product intent belongs. Section headers mirror
/// `templates/spec.template.md`; a test enforces the parity.
library;

/// Screen-ID prefixes reserved for factory-provided screens.
const reservedPrefixes = {'SYS', 'ONB', 'AUTH', 'PAY', 'SET', 'NTF'};

String _s(Object? v, [String fallback = '']) {
  final s = v?.toString().trim();
  return (s == null || s.isEmpty) ? fallback : s;
}

/// Derives a stable screen-ID prefix per feature tab: the first 3 letters of
/// the tab id, uppercased; collisions (with reserved prefixes or each other)
/// extend to 4+ letters, then fall back to a numeric suffix. Prefixes are
/// permanent once code references them - rename only before building.
Map<String, String> tabPrefixes(List<Map> tabs) {
  final out = <String, String>{};
  final taken = {...reservedPrefixes};
  for (final t in tabs) {
    final id = _s(t['id'], 'tab');
    final letters = id.replaceAll(RegExp('[^a-zA-Z]'), '').toUpperCase();
    var prefix = letters.length >= 3 ? letters.substring(0, 3) : letters;
    var len = 3;
    while (taken.contains(prefix) && len < letters.length) {
      len++;
      prefix = letters.substring(0, len);
    }
    var n = 2;
    while (taken.contains(prefix)) {
      prefix = '${letters.substring(0, letters.length.clamp(0, 3))}$n';
      n++;
    }
    taken.add(prefix);
    out[id] = prefix;
  }
  return out;
}

String _todo(String hint) => '**TODO** - $hint';

/// Renders the spec skeleton. [date] is injected (never read from the clock)
/// so output is reproducible.
String generateSpec(Map manifest, {required String date}) {
  final identity = (manifest['identity'] as Map?) ?? const {};
  final brand = (manifest['brand'] as Map?) ?? const {};
  final palette = (brand['palette'] as Map?) ?? const {};
  final fonts = (brand['fonts'] as Map?) ?? const {};
  final nav = (manifest['navigation'] as Map?) ?? const {};
  final auth = (manifest['auth'] as Map?) ?? const {};
  final mon = (manifest['monetization'] as Map?) ?? const {};
  final trial = (mon['trial'] as Map?) ?? const {};
  final features = (manifest['features'] as Map?) ?? const {};

  final name = _s(identity['name'], 'App');
  final slug = _s(identity['slug'], 'app');
  final tagline = _s(identity['tagline']);
  final tabs = ((nav['tabs'] as List?) ?? const [])
      .whereType<Map>()
      .toList(growable: false);
  final featureTabs =
      tabs.where((t) => t['type'] == 'feature').toList(growable: false);
  final builtinTabs =
      tabs.where((t) => t['type'] == 'builtin').toList(growable: false);
  final primary = nav['primary_action'] as Map?;
  final prefixes = tabPrefixes(featureTabs);
  final providers = ((auth['providers'] as List?) ?? const [])
      .map((e) => '$e')
      .toList(growable: false);
  final guestMode = auth['guest_mode'] == true;
  final gates = ((mon['gates'] as List?) ?? const [])
      .map((e) => '$e')
      .toList(growable: false);
  final products = ((mon['products'] as List?) ?? const [])
      .whereType<Map>()
      .toList(growable: false);
  final model = _s(mon['model'], 'subscription');
  final entitlement = _s(mon['entitlement'], 'pro');
  final trialType = _s(trial['type'], 'none');
  final trialDays = (trial['duration_days'] as num?)?.toInt() ?? 0;
  final notifications = features['notifications'] == true;

  final b = StringBuffer();

  // ---- header + how to read ------------------------------------------
  b.writeln('# $name · Product Spec');
  b.writeln('**Version 0.1 · $date · Status: draft**');
  b.writeln();
  b.writeln('<!-- Generated by tools/spec_gen from surge.manifest.yaml. '
      'Regenerating overwrites this file: write freely once, regenerate '
      'never (or diff by hand). Flip Status to "final" when Sections 1-6, '
      '8, and 10 are written - that is what "the idea is fleshed out" '
      'means. -->');
  b.writeln();
  b.writeln('## 0. How to read this document');
  b.writeln();
  b.writeln('- Every screen appears in Section 6 with a unique ID. If it is '
      'not listed, it does not exist.');
  b.writeln('- Phase tags: **[P0]** launch build, **[P1]** fast follow, '
      '**[P2]** later.');
  b.writeln('- Color/type references use surge_ui token and style names, '
      'never raw hex.');
  b.writeln('- Section 8 is the QA checklist: every line is an acceptance '
      'criterion.');
  b.writeln('- This is a **living document with as-built deviations**: when '
      'implementation changes a decision, add a numbered footnote at the '
      'affected spot (`> **Deviation N (date):** what changed and why`) '
      'instead of rewriting history.');
  b.writeln();

  // ---- 1. product overview -------------------------------------------
  b.writeln('## 1. Product overview');
  b.writeln();
  b.writeln('- **One-liner:** '
      '${tagline.isEmpty ? _todo('what + for whom + the hook, one sentence') : tagline}');
  b.writeln('- **Positioning rule:** ${_todo('the one sentence that settles '
      'disputed design calls (what this reads as; what must never leak in)')}');
  b.writeln('- **The core loop:** ${_todo('A -> B -> C -> state compounds; '
      'design for this above all')}');
  b.writeln('- **The quality bar:** ${_todo('the ONE behavior that must be '
      'flawless because incumbents fail it')}');
  b.writeln('- **Platforms:** iOS first, Flutter. Design at 393x852; verify '
      '375x667 and 430x932. Android follows with platform back gestures.');
  b.writeln();

  // ---- 2. design language --------------------------------------------
  b.writeln('## 2. Design language');
  b.writeln();
  b.writeln('Provided by **surge_ui**, themed from the manifest palette: '
      'accent `${_s(palette['accent'], '#75D8FF')}`, accent_soft '
      '`${_s(palette['accent_soft'], '#2B89D8')}`, panel '
      '`${_s(palette['panel'], '#0E1B27')}` · fonts '
      '${_s(fonts['display'], 'Inter')} (display) / '
      '${_s(fonts['text'], 'Inter')} (text). Do not respecify tokens, type, '
      'spacing, or components here.');
  b.writeln();
  b.writeln('- **Domain tokens:** ${_todo('extra semantic colors beyond '
      'SurgeTokens, with light+dark values and a usage rule - or "none"')}');
  b.writeln('- **Signature moment:** ${_todo('the ONE place motion shows '
      'off; everything else uses stock surge_ui motion')}');
  b.writeln('- **New components:** ${_todo('check surge_ui/catalog.json '
      'first; reusable things go INTO surge_ui, not the app')}');
  b.writeln();

  // ---- 3. information architecture -----------------------------------
  b.writeln('## 3. Information architecture');
  b.writeln();
  b.writeln('### 3.1 Tab map');
  b.writeln();
  for (var i = 0; i < tabs.length; i++) {
    final t = tabs[i];
    final builtin = t['type'] == 'builtin';
    b.writeln('${i + 1}. **${_s(t['label'])}** (`${_s(t['id'])}`, icon '
        '`${_s(t['icon'])}`)${builtin ? ' - builtin settings stack' : ''}');
  }
  if (primary != null) {
    b.writeln('- Center action: **${_s(primary['label'])}** '
        '(`${_s(primary['id'])}`, icon `${_s(primary['icon'])}`) - opens a '
        'sheet, never a tab screen.');
  }
  b.writeln();
  b.writeln('### 3.2 Screen inventory');
  b.writeln();
  b.writeln('Add every new screen here WITH an ID before speccing it in '
      'Section 6.');
  b.writeln();
  b.writeln('| ID | Screen | Phase | Source |');
  b.writeln('|---|---|---|---|');
  b.writeln('| SYS-01 | Launch / splash | P0 | foundation |');
  b.writeln('| ONB-01 | Onboarding flow (steps TODO) | P0 | foundation + '
      'surge_onboarding |');
  b.writeln('| AUTH-01 | Sign in (${providers.join(', ')}'
      '${guestMode ? ', guest mode' : ''}) | P0 | foundation |');
  if (providers.contains('email')) {
    b.writeln('| AUTH-02 | Sign up (email) | P0 | foundation |');
  }
  b.writeln('| PAY-01 | Paywall | P0 | foundation |');
  b.writeln('| SET-01 | Settings home | P0 | foundation |');
  b.writeln('| SET-02 | Account (delete account, sign out) | P0 | '
      'foundation |');
  b.writeln('| SET-03 | Legal (privacy, terms) | P0 | foundation |');
  for (final t in featureTabs) {
    final p = prefixes[_s(t['id'])];
    b.writeln('| $p-01 | ${_s(t['label'])} home | P0 | you |');
    b.writeln('| $p-02… | ${_todo('every further ${_s(t['label'])} screen')} '
        '| | you |');
  }
  b.writeln();
  b.writeln('### 3.3 Deep links');
  b.writeln();
  final linkParts = <String>[
    for (final t in featureTabs) '`$slug://${_s(t['id'])}`',
    '`$slug://paywall?src={gateId}`',
  ];
  b.writeln('${linkParts.join(' · ')} - '
      '${_todo('entity links, e.g. `$slug://<thing>/{id}`')}');
  b.writeln();

  // ---- 4. global behaviors -------------------------------------------
  b.writeln('## 4. Global behaviors');
  b.writeln();
  b.writeln('### 4.1 Free tier definition');
  b.writeln();
  b.writeln(_todo('what free includes, as a list, written BEFORE the gates - '
      'free is the product most users experience, and review requires the '
      'app to be usable without paying'));
  b.writeln();
  b.writeln('### 4.2 Gating table');
  b.writeln();
  b.writeln('Standard behavior for every gate: the feature is always visible, '
      'marked with the plus-style chip, tap opens PAY-01 with `?src={gateId}`, '
      'user returns exactly where they were on dismiss. Never disabled-gray, '
      'never hidden. In code: `ref.gate(context, gateId, onSuccess)`.');
  b.writeln();
  if (gates.isEmpty) {
    b.writeln(_todo('no gates in the manifest - a paid app with nothing '
        'gated means the paywall IS the app (app_gated trial); say so here'));
  } else {
    b.writeln('| Gated feature | Gate ID | Trigger point |');
    b.writeln('|---|---|---|');
    for (final g in gates) {
      b.writeln('| ${_todo('name it')} | `$g` | '
          '${_todo('the exact tap/moment that hits the gate')} |');
    }
  }
  b.writeln();
  b.writeln('### 4.3 Monetization mechanics');
  b.writeln();
  b.writeln('- Model: **$model** · entitlement `$entitlement`');
  for (final p in products) {
    final price = p['reference_price'];
    final period = _s(p['period']);
    b.writeln('- Product `${_s(p['id'])}` (${_s(p['type'])}'
        '${period.isEmpty ? '' : ', $period'}'
        '${price == null ? '' : ', ref \$$price'}'
        '${p['default'] == true ? ', default' : ''})');
  }
  switch (trialType) {
    case 'store_intro_offer':
      b.writeln('- Trial: $trialDays-day store intro offer on the '
          'subscription (configure in App Store Connect / Play + '
          'RevenueCat).');
    case 'app_gated':
      b.writeln('- Trial: $trialDays-day app-gated window enforced in-app '
          '(Remote Config key `trial_days`); full access during the window, '
          'then gates arm.');
    default:
      b.writeln('- Trial: none.');
  }
  b.writeln('- ${_todo('meter mechanics if any gate is a metered allowance: '
      'what counts, what does not, reset schedule, where the meter shows')}');
  b.writeln();
  b.writeln('### 4.4 Offline & sync stance');
  b.writeln();
  b.writeln(_todo('which surfaces are local-first and editable offline; what '
      'queues; what requires network. Factory default for conflicts: '
      'last-write-wins per field'));
  b.writeln();
  b.writeln('### 4.5 Error taxonomy');
  b.writeln();
  b.writeln('Factory standard copy applies: offline banner ("You\'re '
      'offline. We\'ll retry automatically."), server-error toast + retry, '
      'auth-expired modal, purchase-fail inline ("You haven\'t been '
      'charged."). Errors never apologize with "Sorry", never blame the '
      'user, always state what happened + the next step. Destructive '
      'confirmations always name the object.');
  b.writeln();
  b.writeln(_todo('domain error classes only (e.g. Ladle\'s import-parse '
      'failures with per-cause recovery)'));
  b.writeln();

  // ---- 5. copy & tone --------------------------------------------------
  b.writeln('## 5. Copy & tone');
  b.writeln();
  b.writeln('Factory rules: sentence case everywhere; the verb on a button '
      'matches its toast and menu item; numerals always ("4 servings", '
      'never "four"); no em dashes in user-facing copy; empty states invite '
      'action, never apologize.');
  b.writeln();
  b.writeln('- **Banned vocabulary:** ${_todo('the words that would betray '
      'this product\'s values (Ladle banned diet-culture language '
      'app-wide)')}');
  b.writeln('- **Voice notes:** ${_todo('2-3 lines max')}');
  b.writeln();

  // ---- 6. screens -------------------------------------------------------
  b.writeln('## 6. Screen-by-screen specification');
  b.writeln();
  b.writeln('Format per screen: **Purpose** (one line) · **Layout** '
      '(top->bottom) · **Interactions** (every tappable element) · '
      '**States** (loading / empty / error / edge) · **Navigation** (in '
      'and out).');
  b.writeln();
  b.writeln('### Factory screens (provided - spec only the deltas)');
  b.writeln();
  b.writeln('- **SYS-01 · Launch.** Solid background, centered glyph, no '
      'spinner; proceed with cached defaults if config is slow.');
  b.writeln('- **ONB-01 · Onboarding.** surge_onboarding data-driven flow. '
      '${_todo('define the steps: welcome, value moments, the aha moment '
      'that seeds first content, notification pre-permission if used')}');
  b.writeln('- **AUTH-01${providers.contains('email') ? '/02' : ''} · '
      'Sign in${providers.contains('email') ? ' / sign up' : ''}.** '
      'Providers: ${providers.join(', ')}'
      '${guestMode ? '; guest mode ON - first sync-required feature prompts '
          'for an account' : ''}. Customize copy only.');
  b.writeln('- **PAY-01 · Paywall.** Foundation layout; write the contextual '
      'headline per gate `src` here: '
      '${gates.isEmpty ? _todo('default headline') : gates.map((g) => '`$g` -> ${_todo('headline')}').join(' · ')}');
  b.writeln('- **SET-01/02/03 · Settings, account, legal.** Provided. '
      'Add app-specific rows (preferences, data controls) as deltas here.');
  b.writeln();
  for (final t in featureTabs) {
    final p = prefixes[_s(t['id'])];
    final label = _s(t['label']);
    b.writeln('### $p-01 · $label home [P0]');
    b.writeln();
    b.writeln('- **Purpose:** ${_todo('one line')}');
    b.writeln('- **Layout:** ${_todo('top->bottom, referencing surge_ui '
        'components by name')}');
    b.writeln('- **Interactions:** ${_todo('every tappable element and what '
        'it does')}');
    b.writeln('- **States:** ${_todo('loading / empty (first-run invite - '
        'this screen is the first thing users see) / error / edge')}');
    b.writeln('- **Navigation:** ${_todo('in and out, including deep '
        'links')}');
    b.writeln();
  }
  if (builtinTabs.isNotEmpty) {
    b.writeln('### ${_s(builtinTabs.first['label'])} tab');
    b.writeln();
    b.writeln('Renders the settings stack (SET-01). Spec additional rows as '
        'SET-01 deltas above.');
    b.writeln();
  }

  // ---- 7. notifications -------------------------------------------------
  b.writeln('## 7. Notifications');
  b.writeln();
  if (notifications) {
    b.writeln('Factory rules: max 1 reminder-class notification per day; '
        'quiet hours 9:30 PM-8:00 AM local; transactional exempt; every '
        'push deep-links; no guilt or streak language.');
    b.writeln();
    b.writeln('| ID | Type | Trigger | Default timing | Copy | Deep link |');
    b.writeln('|---|---|---|---|---|---|');
    b.writeln('| NTF-01 | ${_todo('reminder type')} | ${_todo('condition')} '
        '| ${_todo('day/time')} | ${_todo('final copy in quotes')} | '
        '${_todo('screen ID')} |');
  } else {
    b.writeln('Not in v1 (`features.notifications: false`). If that '
        'changes: flip the manifest flag and spec the table here (ID / '
        'type / trigger / timing / copy / deep link) under the factory '
        'rules: max 1 reminder-class per day, quiet hours, every push '
        'deep-links, no guilt or streak language.');
  }
  b.writeln();

  // ---- 8. edge cases ------------------------------------------------------
  b.writeln('## 8. Edge-case master list (QA checklist)');
  b.writeln();
  b.writeln('Every line becomes a test. The factory covers its own: auth '
      'state transitions, purchase restore/cancel, onboarding re-entry, '
      'settings persistence. List the DOMAIN edges below - aim for 5+ per '
      'feature tab; if you can\'t name 5, the feature isn\'t specced yet.');
  b.writeln();
  for (final t in featureTabs) {
    b.writeln('- **${_s(t['label'])}:** ${_todo('weird inputs · concurrent '
        'edits · empty->full transitions · deleted-thing-still-referenced · '
        'scale (200+ items)')}');
  }
  b.writeln('- **System:** Dynamic Type AX sizes on the densest screen · '
      'VoiceOver full pass on the core loop · Reduce Motion alternates · '
      'offline behavior per 4.4.');
  b.writeln();

  // ---- 9. brand -----------------------------------------------------------
  b.writeln('## 9. Brand');
  b.writeln();
  b.writeln('- **Name:** $name'
      '${tagline.isEmpty ? '' : ' · **Tagline:** "$tagline"'}');
  b.writeln('- **Palette:** accent `${_s(palette['accent'], '#75D8FF')}` · '
      'accent_soft `${_s(palette['accent_soft'], '#2B89D8')}` · panel '
      '`${_s(palette['panel'], '#0E1B27')}` · logo mode '
      '${_s(brand['logo_mode'], 'wordmark')}');
  b.writeln('- **App icon:** ${_todo('describe the mark; provide 1024 '
      'master + dark variant')}');
  b.writeln('- **Marketing screenshots:** frame 1 mirrors the signature '
      'moment (Section 2).');
  b.writeln();

  // ---- 10 + 11 --------------------------------------------------------------
  b.writeln('## 10. Intentionally out of scope (do not design)');
  b.writeln();
  b.writeln(_todo('the features you are deliberately NOT building, so nobody '
      'designs around their future existence - specific, not generic'));
  b.writeln();
  b.writeln('## 11. Open questions');
  b.writeln();
  b.writeln('${_todo('only questions that block a P0 decision')} - '
      'everything else in this document is decided once Status says final.');

  return b.toString();
}
