import 'dart:io';

import 'package:ship_check/ship_check.dart';
import 'package:test/test.dart';

Map manifest({bool tracking = false}) => {
      'legal': {
        'privacy_url': 'https://surgestudios.dev/x/privacy',
        'data_practices': {'tracking': tracking},
      },
    };

/// Lays down a ship-ready fixture app; individual tests then break one thing.
Directory readyApp() {
  final d = Directory.systemTemp.createTempSync('shipcheck');
  void put(String rel, String content) {
    final f = File('${d.path}/$rel');
    f.parent.createSync(recursive: true);
    f.writeAsStringSync(content);
  }

  put('pubspec.yaml', 'name: x\nversion: 1.0.0+1\n');
  put('lib/app/bootstrap.dart',
      'const bool useFirebase = true;\nconst bool useRevenueCat = true;\n');
  put('lib/firebase_options.dart', '// generated by flutterfire\n');
  put('lib/features/counters/counters_screen.dart', 'class C {}\n');
  put('ios/Runner/PrivacyInfo.xcprivacy', '<plist/>');
  put('ios/Runner/Info.plist', '<plist></plist>');
  put('ios/Runner.xcodeproj/project.pbxproj',
      '... PrivacyInfo.xcprivacy in Resources ...');
  put('legal/legal.json', '{}');
  put('legal/privacy.md', '# Privacy');
  put('ANALYTICS.md', '# Analytics');
  put('fastlane/metadata/en-US/name.txt', 'X');
  put('fastlane/metadata/en-US/subtitle.txt', 'Short subtitle');
  put('fastlane/metadata/en-US/keywords.txt', 'a,b,c');
  put('fastlane/metadata/android/en-US/short_description.txt', 'Short.');
  put('firestore.rules', 'rules_version = \'2\';');
  return d;
}

CheckResult byName(List<CheckResult> rs, String name) =>
    rs.firstWhere((r) => r.name == name);

void main() {
  test('a ship-ready app passes every check', () async {
    final d = readyApp();
    final rs = await runChecks(d.path, manifest());
    expect(rs.where((r) => r.status == CheckStatus.fail), isEmpty,
        reason: rs.map((r) => '${r.name}:${r.detail}').join('\n'));
    expect(report(rs, StringBuffer()), 0);
    d.deleteSync(recursive: true);
  });

  test('remaining stubs, mock seams, and placeholder options all block',
      () async {
    final d = readyApp();
    File('${d.path}/lib/features/insights/insights_screen.dart')
      ..createSync(recursive: true)
      ..writeAsStringSync("const s = 'This tab is a wired stub';");
    File('${d.path}/lib/app/bootstrap.dart').writeAsStringSync(
        'const bool useFirebase = false;\nconst bool useRevenueCat = false;\n');
    File('${d.path}/lib/firebase_options.dart')
        .writeAsStringSync('/// PLACEHOLDER. Run flutterfire configure.');

    final rs = await runChecks(d.path, manifest());
    expect(byName(rs, 'feature stubs').status, CheckStatus.fail);
    expect(byName(rs, 'firebase seam').status, CheckStatus.fail);
    expect(byName(rs, 'revenuecat seam').status, CheckStatus.fail);
    expect(byName(rs, 'firebase options').status, CheckStatus.fail);
    expect(report(rs, StringBuffer()), 1);
    d.deleteSync(recursive: true);
  });

  test('tracking=true without an ATT string blocks; with it, passes',
      () async {
    final d = readyApp();
    var rs = await runChecks(d.path, manifest(tracking: true));
    expect(byName(rs, 'att string').status, CheckStatus.fail);

    File('${d.path}/ios/Runner/Info.plist').writeAsStringSync(
        '<key>NSUserTrackingUsageDescription</key><string>why</string>');
    rs = await runChecks(d.path, manifest(tracking: true));
    expect(byName(rs, 'att string').status, CheckStatus.pass);
    d.deleteSync(recursive: true);
  });

  test('hardcoded RevenueCat keys and oversize metadata block', () async {
    final d = readyApp();
    File('${d.path}/lib/app/bootstrap.dart').writeAsStringSync(
        "const bool useFirebase = true;\nconst bool useRevenueCat = true;\n"
        "const k = 'appl_AbCdEfGhIjKlMnOp';\n");
    File('${d.path}/fastlane/metadata/en-US/keywords.txt')
        .writeAsStringSync('k' * 120);

    final rs = await runChecks(d.path, manifest());
    expect(byName(rs, 'secrets hygiene').status, CheckStatus.fail);
    expect(byName(rs, 'store metadata').status, CheckStatus.fail);
    d.deleteSync(recursive: true);
  });

  test('hardcoded PostHog keys block; missing ANALYTICS.md only warns',
      () async {
    final d = readyApp();
    File('${d.path}/lib/features/counters/counters_screen.dart')
        .writeAsStringSync("const k = 'phc_AbCdEfGhIjKlMnOpQr';\n");
    File('${d.path}/ANALYTICS.md').deleteSync();

    final rs = await runChecks(d.path, manifest());
    expect(byName(rs, 'secrets hygiene').status, CheckStatus.fail);
    expect(byName(rs, 'analytics doc').status, CheckStatus.warn);
    d.deleteSync(recursive: true);
  });

  test('privacy manifest missing from the Xcode project is a warning',
      () async {
    final d = readyApp();
    File('${d.path}/ios/Runner.xcodeproj/project.pbxproj')
        .writeAsStringSync('no reference here');
    final rs = await runChecks(d.path, manifest());
    expect(byName(rs, 'privacy manifest').status, CheckStatus.warn);
    expect(report(rs, StringBuffer()), 0); // warns do not block
    d.deleteSync(recursive: true);
  });
}
