import 'dart:convert';
import 'dart:io';

/// Regenerates catalog.json from the `Catalog:` doc headers on components, so
/// the machine index can't drift from source.
///
///   dart run tool/build_catalog.dart          # rewrite catalog.json
///   dart run tool/build_catalog.dart --check   # exit 1 if out of date (CI)
///
/// Run from the surge_ui package root. `since` is preserved from the existing
/// catalog.json (new components default to the current catalog version).
const _allowedKeys = {
  'name',
  'category',
  'summary',
  'whenToUse',
  'variants',
  'tags',
  'since',
};

void main(List<String> args) {
  final check = args.contains('--check');

  // Existing catalog: keep version + per-component `since`.
  final catalogFile = File('catalog.json');
  var version = '0.1.0';
  final sinceByName = <String, String>{};
  if (catalogFile.existsSync()) {
    final existing = jsonDecode(catalogFile.readAsStringSync()) as Map;
    version = (existing['version'] as String?) ?? version;
    for (final c in (existing['components'] as List? ?? [])) {
      final m = c as Map;
      sinceByName[m['name'] as String] = (m['since'] as String?) ?? version;
    }
  }

  final components = <Map<String, Object?>>[];
  final dartFiles = Directory('lib/src')
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  for (final file in dartFiles) {
    // listSync on the relative Directory('lib/src') already yields cwd-relative
    // paths; just normalize separators to posix.
    final rel = file.path.replaceAll(r'\', '/');
    for (final entry in _parseFile(file.readAsLinesSync())) {
      entry['since'] = sinceByName[entry['name']] ?? version;
      entry['import'] = 'package:surge_ui/surge_ui.dart';
      entry['file'] = rel;
      components.add(entry);
    }
  }

  components.sort((a, b) {
    final byCat = (a['category'] as String).compareTo(b['category'] as String);
    return byCat != 0
        ? byCat
        : (a['name'] as String).compareTo(b['name'] as String);
  });

  final out = <String, Object?>{
    r'$comment':
        'Machine-readable index of surge_ui. Generated by tool/build_catalog.dart '
            'from the Catalog: doc headers - do not hand-edit. Search before writing custom UI.',
    'version': version,
    'components': components,
  };
  final rendered = '${const JsonEncoder.withIndent('  ').convert(out)}\n';

  if (check) {
    final current = catalogFile.existsSync() ? catalogFile.readAsStringSync() : '';
    if (current.trim() != rendered.trim()) {
      stderr.writeln(
        'catalog.json is out of date. Run: dart run tool/build_catalog.dart',
      );
      exit(1);
    }
    stdout.writeln('catalog.json is up to date (${components.length} components).');
    return;
  }

  catalogFile.writeAsStringSync(rendered);
  stdout.writeln('Wrote catalog.json (${components.length} components).');
}

/// Extract every `Catalog:` block in a file's lines into a field map.
List<Map<String, Object?>> _parseFile(List<String> lines) {
  final entries = <Map<String, Object?>>[];
  Map<String, Object?>? current;
  String? lastKey;

  void flush() {
    if (current != null && current!['name'] != null) entries.add(current!);
    current = null;
    lastKey = null;
  }

  for (final raw in lines) {
    final line = raw.trimLeft();
    if (current == null) {
      if (line.trimRight() == '/// Catalog:') {
        current = <String, Object?>{};
        lastKey = null;
      }
      continue;
    }
    // In a block.
    if (!line.startsWith('///')) {
      flush();
      continue;
    }
    final content = line.length > 3 ? line.substring(3).trim() : '';
    if (content.isEmpty) {
      flush(); // blank comment line ends the header (prose follows)
      continue;
    }
    final colon = content.indexOf(': ');
    final key = colon > 0 ? content.substring(0, colon) : '';
    if (colon > 0 && _allowedKeys.contains(key)) {
      final value = content.substring(colon + 2).trim();
      if (key == 'variants' || key == 'tags') {
        current![key] =
            value.split(',').map((s) => s.trim()).where((s) => s.isNotEmpty).toList();
      } else {
        current![key] = value;
      }
      lastKey = key;
    } else if (lastKey != null && lastKey != 'variants' && lastKey != 'tags') {
      // Continuation of a wrapped value (e.g. a long whenToUse).
      current![lastKey!] = '${current![lastKey!]} $content';
    }
  }
  flush();
  return entries;
}
