import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:purchases_flutter/purchases_flutter.dart';
// import 'firebase_options.dart'; // generated by `flutterfire configure` in init

/// App bootstrap: init Firebase, RevenueCat, Crashlytics, then run the app.
/// SKELETON. firebase_options.dart and the RevenueCat key are produced by
/// scripts/forge.sh; this won't run until init has been done.
Future<void> bootstrap(Widget Function() builder) async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(/* options: DefaultFirebaseOptions.currentPlatform */);

  // FlutterError.onError -> FirebaseCrashlytics.instance.recordFlutterError
  // (wire after flutterfire configure provides the options).

  await Purchases.configure(
    PurchasesConfiguration(const String.fromEnvironment('REVENUECAT_KEY')),
  );

  runApp(ProviderScope(child: builder()));
}
