import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:lucide_icons/lucide_icons.dart';

import '../features/feature_registry.dart'; // generated by the post_gen hook
import '../modules/auth/sign_in_screen.dart';
import '../modules/settings/settings_screen.dart';

/// go_router shell for {{name}}. Tabs come from navigation.tabs in the manifest.
/// Feature tabs resolve through [featureBuilders] (generated per tab); the
/// builtin tab renders the settings stack.
///
/// SKELETON: the StatefulShellRoute shape is correct for go_router 17.x but
/// verify the API against your installed version, and add the auth redirect
/// (signed-out -> /sign-in; respect guest_mode).
typedef TabDef = ({String id, String label, IconData icon, bool builtin});

const List<TabDef> kTabs = [
{{#tabs}}  (id: '{{id}}', label: '{{label}}', icon: LucideIcons.circle, builtin: {{builtin}}),
{{/tabs}}];

Widget _screenFor(BuildContext context, TabDef t) =>
    t.builtin ? const SettingsScreen() : featureBuilders[t.id]!(context);

GoRouter buildRouter() {
  return GoRouter(
    initialLocation: '/${kTabs.first.id}',
    routes: [
      StatefulShellRoute.indexedStack(
        builder: (context, state, shell) => _Shell(shell: shell),
        branches: [
          for (final t in kTabs)
            StatefulShellBranch(routes: [
              GoRoute(path: '/${t.id}', builder: (c, s) => _screenFor(c, t)),
            ]),
        ],
      ),
      GoRoute(path: '/sign-in', builder: (c, s) => const SignInScreen()),
    ],
  );
}

class _Shell extends StatelessWidget {
  const _Shell({required this.shell});
  final StatefulNavigationShell shell;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: shell,
      bottomNavigationBar: NavigationBar(
        selectedIndex: shell.currentIndex,
        onDestinationSelected: (i) =>
            shell.goBranch(i, initialLocation: i == shell.currentIndex),
        destinations: [
          for (final t in kTabs)
            NavigationDestination(icon: Icon(t.icon), label: t.label),
        ],
      ),
    );
  }
}
